name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  fl_chart: ^0.65.0
  money2: ^3.0.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/zeta.jpeg
    - assets/zeta_logo.jpeg
