name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.12.0
  flutter_riverpod: ^2.4.9
  fl_chart: ^0.70.2
  money2: ^3.0.0
  provider: ^6.1.2
  shared_preferences: ^2.0.15
  flutter_slidable: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/zeta.jpeg
    - assets/zeta_logo.jpeg
